name: Gradle & Spring Boot CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build
      
      # 먼저, 빌더 드라이버나 플랫폼 등을 세팅한다.
      # buildx를 통해서 도커 이미지를 빌드하고 푸시하려면 이 과정이 선행되어야 한다.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # 도커 허브에 접근하기 위해서 먼저 로그인을 한다.
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # 이미지를 빌드하고 이를 도커 허브에 푸시한다.
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: devspacehub/devspace:latest
